-- 035: page order and common cohort indexes (CW-20261001-0570).
-- EXPLAIN evidence: docs/list-index-plans.md. No rows are rewritten.
-- Descending sorts still tie-break on id ASC, so reversing an ASC index
-- cannot serve both directions. Keep expression keys identical to the store.
-- SQLite timestamp expressions preserve legacy spellings and nanoseconds.

CREATE INDEX IF NOT EXISTS idx_tasks_page_priority_asc ON tasks (priority ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_tasks_page_priority_desc ON tasks (priority DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_tasks_page_status_asc ON tasks (status ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_tasks_page_status_desc ON tasks (status DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_tasks_page_updated_at_asc ON tasks ((replace(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_tasks_page_updated_at_desc ON tasks ((replace(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_tasks_page_created_at_asc ON tasks ((replace(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_tasks_page_created_at_desc ON tasks ((replace(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_projects_page_name_asc ON projects (name ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_projects_page_name_desc ON projects (name DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_projects_page_status_asc ON projects (status ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_projects_page_status_desc ON projects (status DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_projects_page_updated_at_asc ON projects ((replace(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_projects_page_updated_at_desc ON projects ((replace(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_projects_page_created_at_asc ON projects ((replace(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_projects_page_created_at_desc ON projects ((replace(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_epics_page_name_asc ON epics (name ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_epics_page_name_desc ON epics (name DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_epics_page_status_asc ON epics (status ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_epics_page_status_desc ON epics (status DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_epics_page_updated_at_asc ON epics ((replace(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_epics_page_updated_at_desc ON epics ((replace(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_epics_page_created_at_asc ON epics ((replace(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_epics_page_created_at_desc ON epics ((replace(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_sprints_page_name_asc ON sprints (name ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_sprints_page_name_desc ON sprints (name DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_sprints_page_status_asc ON sprints (status ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_sprints_page_status_desc ON sprints (status DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_sprints_page_updated_at_asc ON sprints ((replace(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_sprints_page_updated_at_desc ON sprints ((replace(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_sprints_page_created_at_asc ON sprints ((replace(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_sprints_page_created_at_desc ON sprints ((replace(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_runs_page_started_at_asc ON runs ((replace(substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_runs_page_started_at_desc ON runs ((replace(substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) DESC, id ASC);
-- Existing idx_runs_status already orders status ASC, integer rowid/id ASC.
CREATE INDEX IF NOT EXISTS idx_runs_page_status_desc ON runs (status DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_runs_page_duration_asc ON runs (COALESCE(CAST(ROUND((julianday((replace(substr(replace(replace(ended_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(ended_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(ended_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END))-julianday((replace(substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END)))*86400000) AS INTEGER), -1) ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_runs_page_duration_desc ON runs (COALESCE(CAST(ROUND((julianday((replace(substr(replace(replace(ended_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(ended_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(ended_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END))-julianday((replace(substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END)))*86400000) AS INTEGER), -1) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_runs_page_cost_asc ON runs (COALESCE(cost, 0) ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_runs_page_cost_desc ON runs (COALESCE(cost, 0) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_tasks_page_status_priority ON tasks (status, priority ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_tasks_page_project_id_priority ON tasks (project_id, priority ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_tasks_page_epic_id_priority ON tasks (epic_id, priority ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_tasks_page_sprint_id_priority ON tasks (sprint_id, priority ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_tasks_page_kind_priority ON tasks (kind, priority ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_tasks_page_parent_id_priority ON tasks (parent_id, priority ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_epics_page_project_updated ON epics (project_id, (replace(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_sprints_page_project_updated ON sprints (project_id, (replace(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(updated_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_runs_page_status_started ON runs (status, (replace(substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_runs_page_task_id_started ON runs (task_id, (replace(substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(started_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_comments_page_created_asc ON comments ((replace(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_comments_page_entity_created_asc ON comments (entity_type, entity_id, (replace(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_comments_page_created_desc ON comments ((replace(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_comments_page_entity_created_desc ON comments (entity_type, entity_id, (replace(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 1, 19), 'T', ' ') || '.' || CASE WHEN substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 20, 1) = '.' THEN substr(substr(replace(replace(created_at, ' +0000 UTC', ''), 'Z', ''), 21) || '000000000', 1, 9) ELSE '000000000' END) DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_artifacts_page_task_created ON artifacts (task_id, created_at ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_sessions_page_created ON sessions (created_at DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_sessions_page_state_created ON sessions (state, created_at DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_sessions_page_project_id_created ON sessions (project_id, created_at DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_sessions_page_task_id_created ON sessions (task_id, created_at DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_messages_page_to_urn_created ON messages (to_urn, created_at ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_messages_page_thread_id_created ON messages (thread_id, created_at ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_collections_page_created ON collections (created_at DESC, id ASC);
CREATE INDEX IF NOT EXISTS idx_checkpoints_page_task_emitted ON checkpoints (task_id, emitted_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_checkpoints_page_pending_emitted ON checkpoints (status, emitted_at ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_templates_page_id_version ON task_templates (id ASC, version DESC) WHERE is_archived = 0;
CREATE INDEX IF NOT EXISTS idx_tasks_page_collection_position ON tasks (collection_id, (collection_position IS NULL), collection_position ASC, created_at ASC);

-- Canonical run-cost aggregation looks up all ledger rows for each run.
CREATE INDEX IF NOT EXISTS idx_cost_run ON cost_ledger (run_id);
