package mcpadapter_test

// Description-inventory test. Dumps every registered tool's name +
// description to the deliverable artifact path so the orchestrator can
// commit the inventory without running the server. Also asserts every
// description meets the Phase C minimums — >= 4 lines and contains an
// example fragment ("Example:") — so drift is caught by CI.

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/hollis-labs/torque/internal/mcpadapter"
)

// descriptionInventoryPath is the orchestrator-facing artifact location.
// The test writes to TORQUE_DESCRIPTION_INVENTORY_PATH if set (so CI
// can redirect), otherwise uses the ticket-prescribed agent-workspaces
// path. Missing parent dir is treated as "artifact emission is optional"
// — the assertions below still run and guard the descriptions in-tree.
const descriptionInventoryPath = "/Users/chrispian/Projects-apps/agent-workspaces/execution/torque/orch-mcp-hardening/2026-04-17/CW-20260418-0013-tool-descriptions.md"

// TestDescriptionInventory_AssertsMinimumsAndEmitsArtifact walks every
// registered tool (core + all opt-in features enabled) and:
//  1. Asserts description >= 4 lines and contains "Example:".
//  2. Writes a markdown inventory to the artifact path if reachable.
//
// This is the test the exit-gate references: "a test that dumps registered
// tool descriptions to the artifact file; parse + assert each has >= 4
// lines and includes an example fragment."
func TestDescriptionInventory_AssertsMinimumsAndEmitsArtifact(t *testing.T) {
	svc := setupServiceDirect(t)
	require.NoError(t, svc.Feature.Enable("sprints"))
	require.NoError(t, svc.Feature.Enable("projects"))
	require.NoError(t, svc.Feature.Enable("epics"))
	a := mcpadapter.New(svc, nil)

	tools := a.Server().ListTools()
	require.NotEmpty(t, tools, "expected registered tools")

	// Gather sorted names so the inventory output is stable across runs.
	names := make([]string, 0, len(tools))
	for name := range tools {
		names = append(names, name)
	}
	sort.Strings(names)

	// Build the markdown artifact as we walk. Assert per tool.
	var md strings.Builder
	md.WriteString("# CW-20260418-0013 — Phase C MCP Tool Description Inventory\n\n")
	md.WriteString("Generated by TestDescriptionInventory_AssertsMinimumsAndEmitsArtifact.\n\n")
	md.WriteString(fmt.Sprintf("**Tool count:** %d (core + sprints + projects + epics).\n\n", len(names)))

	totalLines := 0
	for _, name := range names {
		tool := tools[name]
		desc := tool.Tool.Description
		lines := strings.Split(strings.TrimRight(desc, "\n"), "\n")

		assert.GreaterOrEqual(t, len(lines), 4,
			"%s: description must be >= 4 lines per Phase C contract; got %d", name, len(lines))
		assert.Contains(t, desc, "Example:",
			"%s: description must include an Example: block per Phase C contract", name)
		totalLines += len(lines)

		md.WriteString(fmt.Sprintf("## `%s`\n\n```\n%s\n```\n\n", name, desc))
	}

	// Average is telemetry for the report — not an assertion gate.
	avg := float64(totalLines) / float64(len(names))
	t.Logf("description inventory: %d tools, avg %.1f lines/description", len(names), avg)
	md.WriteString(fmt.Sprintf("\n---\n\n_Average: %.1f lines per description (target 4–8)._\n", avg))

	// Emit the artifact if the parent dir exists; otherwise skip silently.
	// The orchestrator creates the tracking_root before running tests, so
	// in-workspace execution succeeds. CI/sibling-env runs where the path
	// is absent degrade gracefully.
	path := os.Getenv("TORQUE_DESCRIPTION_INVENTORY_PATH")
	if path == "" {
		path = descriptionInventoryPath
	}
	parent := filepath.Dir(path)
	if _, statErr := os.Stat(parent); statErr == nil {
		require.NoError(t, os.WriteFile(path, []byte(md.String()), 0o644),
			"failed to write description inventory to %s", path)
		t.Logf("wrote description inventory to %s (%d bytes)", path, md.Len())
	} else {
		t.Logf("skipping artifact emission: parent dir %s not present", parent)
	}
}
