package mcpadapter

// toolHints is the explicit, hand-reviewed MCP tool-annotation set for
// every tool this adapter registers (CW-20260917-0014). go-mcp requires
// ReadOnlyHint/DestructiveHint/IdempotentHint/OpenWorldHint to be always
// explicit, never inferred from a tool's name by the framework -- this
// table is the human decision the framework refuses to make for us, kept
// as one reviewable, editable fact per tool rather than derived at
// runtime. OpenWorldHint is false for every Torque tool: every tool
// operates on Torque's own closed-domain task/project store, never an
// open-ended external system (even torque_models_list serves a locally
// cached, enumerable catalog). newTool call sites panic via addTool if a
// registered name has no entry here -- add one deliberately rather than
// letting a new tool ship with silently-defaulted hints.
type toolHints struct {
	ReadOnly    bool
	Destructive bool
	Idempotent  bool
}

var toolAnnotations = map[string]toolHints{
	"torque_aar_submit":                {false, false, false},
	"torque_artifact_create":           {false, false, false},
	"torque_artifact_delete":           {false, true, false},
	"torque_artifact_get":              {true, false, true},
	"torque_artifact_list":             {true, false, true},
	"torque_artifact_update":           {false, false, true},
	"torque_broker_inbox":              {true, false, true},
	"torque_broker_request":            {false, false, false},
	"torque_broker_send":               {false, false, false},
	"torque_collection_archive":        {false, false, true},
	"torque_collection_create":         {false, false, false},
	"torque_collection_get":            {true, false, true},
	"torque_collection_inbox_add":      {false, false, false},
	"torque_collection_inbox_list":     {true, false, true},
	"torque_collection_list":           {true, false, true},
	"torque_collection_task_add":       {false, false, false},
	"torque_collection_task_move":      {false, false, true},
	"torque_collection_task_remove":    {false, true, false},
	"torque_collection_task_reorder":   {false, false, true},
	"torque_collection_tasks_list":     {true, false, true},
	"torque_collection_unarchive":      {false, false, true},
	"torque_collection_update":         {false, false, true},
	"torque_comment_add":               {false, false, false},
	"torque_comment_bulk_add":          {false, false, false},
	"torque_comment_delete":            {false, true, false},
	"torque_comment_list":              {true, false, true},
	"torque_comment_search":            {true, false, true},
	"torque_comment_update":            {false, false, true},
	"torque_epic_archive":              {false, false, true},
	"torque_epic_bulk_update":          {false, false, true},
	"torque_epic_create":               {false, false, false},
	"torque_epic_delete":               {false, true, false},
	"torque_epic_get":                  {true, false, true},
	"torque_epic_list":                 {true, false, true},
	"torque_epic_unarchive":            {false, false, true},
	"torque_epic_update":               {false, false, true},
	"torque_health":                    {true, false, true},
	"torque_inbox_poll":                {false, false, true},
	"torque_issue_bulk_transition":     {false, false, true},
	"torque_issue_bulk_update":         {false, false, true},
	"torque_issue_create":              {false, false, false},
	"torque_issue_delete":              {false, true, false},
	"torque_issue_get":                 {true, false, true},
	"torque_issue_list":                {true, false, true},
	"torque_issue_update":              {false, false, true},
	"torque_models_get":                {true, false, true},
	"torque_models_list":               {true, false, true},
	"torque_plan_add_phase":            {false, false, false},
	"torque_plan_create":               {false, false, false},
	"torque_plan_delete":               {false, true, false},
	"torque_plan_get":                  {true, false, true},
	"torque_plan_list":                 {true, false, true},
	"torque_plan_list_children":        {true, false, true},
	"torque_plan_remove_phase":         {false, true, false},
	"torque_plan_start":                {false, false, false},
	"torque_plan_update":               {false, false, true},
	"torque_project_archive":           {false, false, true},
	"torque_project_create":            {false, false, false},
	"torque_project_delete":            {false, true, false},
	"torque_project_get":               {true, false, true},
	"torque_project_list":              {true, false, true},
	"torque_project_unarchive":         {false, false, true},
	"torque_project_update":            {false, false, true},
	"torque_run_get":                   {true, false, true},
	"torque_run_list":                  {true, false, true},
	"torque_scheduler_status":          {true, false, true},
	"torque_scheduler_toggle":          {false, false, false},
	"torque_session_attach":            {false, false, false},
	"torque_session_checkpoint":        {false, false, false},
	"torque_session_create":            {false, false, false},
	"torque_session_get":               {true, false, true},
	"torque_session_launch":            {false, false, false},
	"torque_session_list":              {true, false, true},
	"torque_session_resume":            {false, false, false},
	"torque_session_stop":              {false, false, true},
	"torque_settings_get":              {true, false, true},
	"torque_settings_save":             {false, false, true},
	"torque_sprint_approve":            {false, false, true},
	"torque_sprint_archive":            {false, false, true},
	"torque_sprint_bulk_update":        {false, false, true},
	"torque_sprint_create":             {false, false, false},
	"torque_sprint_delete":             {false, true, false},
	"torque_sprint_get":                {true, false, true},
	"torque_sprint_list":               {true, false, true},
	"torque_sprint_start":              {false, false, false},
	"torque_sprint_unarchive":          {false, false, true},
	"torque_sprint_update":             {false, false, true},
	"torque_steering_dismiss":          {false, false, true},
	"torque_tag_create":                {false, false, false},
	"torque_tag_delete":                {false, true, false},
	"torque_tag_get":                   {true, false, true},
	"torque_tag_list":                  {true, false, true},
	"torque_tag_merge":                 {false, true, false},
	"torque_tag_update":                {false, false, true},
	"torque_task_blocked":              {false, false, true},
	"torque_task_bulk_delete":          {false, true, false},
	"torque_task_bulk_tag":             {false, false, true},
	"torque_task_bulk_transition":      {false, false, true},
	"torque_task_bulk_update":          {false, false, true},
	"torque_task_checkpoint_cancel":    {false, false, false},
	"torque_task_checkpoint_emit":      {false, false, false},
	"torque_task_checkpoint_get":       {true, false, true},
	"torque_task_checkpoint_list":      {true, false, true},
	"torque_task_checkpoint_respond":   {false, false, false},
	"torque_task_checkpoints_pending":  {true, false, true},
	"torque_task_create":               {false, false, false},
	"torque_task_create_from_template": {false, false, false},
	"torque_task_delete":               {false, true, false},
	"torque_task_facets":               {true, false, true},
	"torque_task_get":                  {true, false, true},
	"torque_task_list":                 {true, false, true},
	"torque_task_review":               {false, false, true},
	"torque_task_subtodo_add":          {false, false, false},
	"torque_task_subtodo_bulk_add":     {false, false, false},
	"torque_task_subtodo_delete":       {false, true, false},
	"torque_task_subtodo_done":         {false, false, true},
	"torque_task_subtodo_list":         {true, false, true},
	"torque_task_subtodo_update":       {false, false, true},
	"torque_task_summary":              {false, false, false},
	"torque_task_transition":           {false, false, true},
	"torque_task_update":               {false, false, true},
	"torque_template_archive":          {false, false, true},
	"torque_template_create":           {false, false, false},
	"torque_template_delete":           {false, true, false},
	"torque_template_get":              {true, false, true},
	"torque_template_list":             {true, false, true},
	"torque_template_update":           {false, false, true},
}
