const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright');
import { fileURLToPath } from 'node:url';
const baseURL = process.env.GUI_BASE_URL ?? 'http://127.0.0.1:5218';
import {mkdirSync,writeFileSync} from 'node:fs';
const dir = fileURLToPath(new URL('.', import.meta.url));
mkdirSync(dir,{recursive:true});
const network=[],errors=[];
const date=i=>new Date(Date.UTC(2026,9,1,10,0,i)).toISOString();
const tasks=Array.from({length:301},(_,i)=>({id:`T-${String(i).padStart(3,'0')}`,title:`Task ${i} — production backlog`,description:'',status:'todo',priority:2,kind:'task',manual:true,cost_budget:null,max_duration_ms:null,token_budget:null,max_retries:3,executor:'cli',agent_profile:'',working_dir:'',source_type:'user',source_ref:null,trust:'standard',checkpoint_mode:'none',on_checkpoint_response:'resume',on_done:'review',on_fail:'retry',on_review:'pause',on_done_merge:'none',tools:[],permissions:{},environment:{},system_prompt:'',files:[],escalation_chain:[],quality_gates:[],deliverables:[],deliverable_preset:'',blocked_reason:'',sprint_id:null,project_id:null,epic_id:null,collection_id:'COL-1',created_at:date(i),updated_at:date(i),tags:[],depends_on:[],metadata:{},subtodos:[],stats:{cost:0,run_count:0}}));
const collections=Array.from({length:75},(_,i)=>({id:`COL-${i+1}`,name:i===0?'Engineering backlog':`Collection ${i+1}`,description:'Server-ordered collection',created_at:date(i),updated_at:date(i),archived_at:null}));
const models=Array.from({length:210},(_,i)=>({id:`model-${i}`,name:`Model ${String(i).padStart(3,'0')}`,provider_id:i%2?'peer-b':'peer-a',cost:{input:[10,0,2][i%3],output:5},limit:{context_window:2000+i,max_output_tokens:1000+i},capabilities:{tool_call:true},last_updated:'2026-10-01'}));
const templates=Array.from({length:120},(_,i)=>({id:`TPL-${i}`,version:1,name:`Template ${i}`,kind:'agent',created_at:date(i),updated_at:date(i),is_archived:false,auto_execute:false,required_vars:[],defaults:{}}));
const runs=Array.from({length:120},(_,i)=>({ID:i+1,TaskID:'T-000',Executor:'cli',Status:'completed',StartedAt:date(i),EndedAt:{Valid:true,Time:date(i+2)},PromptTokens:100,CompletionTokens:50,Cost:.02,ExitCode:{Valid:true,Int64:0},ErrorMessage:''}));
const messages=Array.from({length:120},(_,i)=>({id:`MSG-${i}`,kind:'notice',from:'msg://agent/local/peer',to:'msg://user/local/operator',thread_id:'thread-demo',channel:'work',payload:{body:`Message ${i} from the loaded history`},created_at:date(i),delivered_at:date(i+1)}));
const artifacts=Array.from({length:110},(_,i)=>({ID:i+1,TaskID:'T-000',Type:'text',Content:`Artifact ${i}`,CreatedAt:date(i),RunID:null,URL:'',FilePath:''}));
const comments=Array.from({length:130},(_,i)=>({id:i+1,entity_type:'task',entity_id:'T-000',author:'peer',content:`Comment ${i}`,created_at:date(i)}));
const plan=id=>({task:{...tasks[0],id,kind:'plan',title:`Plan ${id}`},plan:{phases:[]},progress:{total_children:301,done:0,by_phase:{}}});
let inboxOffset=0;
function page(items,url,drain=false){const n=Number(url.searchParams.get('limit')||50),at=drain?inboxOffset:Number(url.searchParams.get('cursor')||0),batch=items.slice(at,at+n),more=at+n<items.length;if(drain)inboxOffset+=batch.length;return {items:batch,meta:{returned:batch.length,limit:n,total:drain?items.length-at:items.length,has_more:more,next_cursor:drain?null:more?String(at+n):null}};}
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});
const p=await context.newPage();p.on('pageerror',e=>errors.push(e.stack));
await p.route('**/api/v1/**',async route=>{const url=new URL(route.request().url()),path=url.pathname.replace('/api/v1','');network.push({path,query:Object.fromEntries(url.searchParams),method:route.request().method()});let data={};
if(path==='/features')data={collections:true,projects:true,sprints:true,epics:true};
else if(path==='/collections')data=page(collections,url);
else if(path==='/collections/inbox/tasks')data=page([],url);
else if(/^\/collections\/[^/]+\/tasks$/.test(path))data=page(path.includes('COL-1/')?tasks:[],url);
else if(path==='/models'){let items=models.filter(m=>(!url.searchParams.get('provider')||m.provider_id===url.searchParams.get('provider'))&&(!url.searchParams.get('search')||`${m.id} ${m.name} ${m.provider_id}`.toLowerCase().includes(url.searchParams.get('search').toLowerCase())));const by=url.searchParams.get('sort_by')||'name',dir=url.searchParams.get('sort_dir')==='desc'?-1:1,key=m=>by==='cost'?m.cost.input:by==='context'?m.limit.context_window:by==='output'?m.limit.max_output_tokens:m[by==='provider_id'?'provider_id':by];items.sort((a,b)=>dir*(key(a)<key(b)?-1:key(a)>key(b)?1:0)||`${a.provider_id}/${a.id}`.localeCompare(`${b.provider_id}/${b.id}`));data=page(items,url);}
else if(path==='/templates')data=page(templates,url);
else if(path==='/plans')data=page(tasks.slice(0,120).map(t=>({...t,kind:'plan'})),url);
else if(/^\/plans\/[^/]+\/children$/.test(path))data=page(tasks,url);
else if(/^\/plans\/[^/]+$/.test(path))data=plan(path.split('/')[2]);
else if(path==='/messages/inbox')data=page(messages,url,true);
else if(path.startsWith('/messages/thread/'))data=page([...messages].reverse(),url);
else if(path==='/tasks/T-000')data=tasks[0];
else if(path.endsWith('/artifacts'))data=page(artifacts,url);
else if(path==='/comments'||path.endsWith('/comments'))data=page(comments,url);
else if(path==='/runs')data=page(url.searchParams.get('status')==='running'?[]:[...runs].reverse(),url);
else if(path==='/tasks')data=page(tasks,url);
else if(path.endsWith('/checkpoints'))data=page([],url);
else if(path.includes('events')||path.includes('stream'))return route.fulfill({status:200,contentType:'text/event-stream',body:': fixture\n\n'});
else if(path.includes('facets'))data={dimensions:[],total:301,matching_count:301,facets:{}};
else if(path.includes('rollup'))data={groups:[]};
return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)});});
const capture=async name=>p.screenshot({path:`${dir}/${name}.png`});
await p.goto(`${baseURL}/collections`);await p.getByText('Task 49 — production backlog').waitFor();await capture('01-collections-first-page');
let before=network.filter(r=>r.path==='/collections/COL-1/tasks').length;if(network.some(r=>r.path==='/collections/COL-1/tasks'&&r.query.cursor))throw Error('collection auto exhausted');await p.getByRole('button',{name:'Load more tasks',exact:true}).click();await p.getByText('Task 99 — production backlog').waitFor();if(network.filter(r=>r.path==='/collections/COL-1/tasks').length!==before+1)throw Error('task continuation not bounded');await capture('02-collections-task-continuation');
await p.goto(`${baseURL}/models`);await p.getByText('Model 000',{exact:true}).waitFor();await p.getByText('$/M In',{exact:true}).click();await p.waitForTimeout(350);await capture('03-models-server-cost-sort');await p.getByPlaceholder('Search id or name…').fill('Model 209');await p.getByText('Model 209',{exact:true}).waitFor();await capture('04-models-server-search');
await p.goto(`${baseURL}/templates`);await p.getByText('Template 49',{exact:true}).waitFor();await capture('05-templates-page');
await p.goto(`${baseURL}/plans`);await p.getByText('Plan T-049',{exact:true}).waitFor();await capture('06-plans-page');
await p.goto(`${baseURL}/messaging`);await p.getByRole('textbox',{name:'Inbox address URN'}).fill('msg://user/local/operator');if(network.some(r=>r.path==='/messages/inbox'))throw Error('inbox drained automatically');await p.getByRole('button',{name:'Receive batch',exact:true}).click();await p.getByRole('button',{name:'Receive next batch',exact:true}).waitFor();await p.getByRole('button').filter({hasText:'peer'}).first().click();await p.getByRole('button',{name:'Load more history messages',exact:true}).waitFor();await capture('07-messaging-explicit-batch-thread');await p.getByRole('button',{name:'Load more history messages',exact:true}).click();await p.waitForTimeout(350);await capture('08-messaging-thread-continuation');
await p.goto(`${baseURL}/dashboard/_widget-preview`);await p.waitForTimeout(1500);await capture('09-widgets-loaded-pages');await p.getByRole('button',{name:'Load more tasks',exact:true}).waitFor();
await p.goto(`${baseURL}/tasks/T-000`);await p.getByRole('tab',{name:/Logs/}).click();await p.getByRole('button',{name:'Load more artifacts',exact:true}).waitFor();await p.getByRole('button',{name:'Load more comments',exact:true}).waitFor();await p.getByRole('button',{name:'Load more runs',exact:true}).waitFor();await capture('10-activity-loaded-source-pages');
writeFileSync(`${dir}/network.json`,JSON.stringify({fixture_sizes:{collections:75,tasks:301,models:210,templates:120,runs:120,messages:120,comments:130,artifacts:110},requests:network,errors},null,2));await browser.close();if(errors.length)throw Error(errors.join('\n'));console.log('Screenshots and request assertions passed');
