package agent

import (
	"context"
	"errors"
	"fmt"

	"github.com/hollis-labs/clockwork-manifold/internal/persistence/sqlstore"
)

// ResumeSession resumes a previously booted session by sessionID using the
// per-session state persisted on the sessions row (AgentProfile, Workdir,
// ProjectID, TaskID, the provider session-id captured in the resume_hint
// column by the OnSessionID callback during the original boot). Falls back
// to fresh-boot when ProviderCapabilities(provider).SupportsResume is false
// — capability check is the single decision point per sprint-α D4 (no per-
// call probes, no try-resume-then-fallback runtime detection).
//
// Lifecycle: returns a freshly-booted (or freshly-resumed) *Session in the
// long-lived mode. Callers can then SendInput / Attach / Stop / Wait
// through the standard Manager surface. The α.4 (HITL response) path calls
// ResumeSession + SendInput; the α.5 (stuck-task recovery) path
// checkpoints the session, calls ResumeSession with DiagnosticNote set so
// the resumed transcript prepends an operator note, then optionally
// SendInputs follow-up instructions.
//
// Resume vs fresh-boot:
//
//   - SupportsResume=true (claude — and codex as of α.1's declared
//     capability, though the codex go-providers v0.16.1 adapter does not
//     yet thread cliSessionID into argv): the persisted resume_hint is
//     threaded into Options.ProviderSessionIDOverride; Boot sets
//     StartOptions.SessionIDPreset; the claude adapter prepends
//     `--resume <session-id>` to argv on the first turn after Start.
//   - SupportsResume=false (gemini, copilot, opencode): fresh-boot —
//     same AgentProfile / Workdir / ProjectID / TaskID rehydration, no
//     SessionIDPreset, no `--resume` in argv. The new boot gets a fresh
//     session-id; the prior session's transcript is NOT recovered (and
//     was never going to be on these adapters — their CLIs lack a native
//     resume primitive).
//
// Boot-dir handling: Boot plants a fresh per-task tempdir + CLAUDE.md +
// `.mcp.json` on every call. ResumeSession does NOT attempt to re-use the
// prior session's boot-dir — that dir was tied to the original Manager
// process's loopback URL and may have been torn down by teardownSession.
// The fresh plant binds the new loopback (rebound to 127.0.0.1) and the
// resumed agent sees the new MCP loopback URL on first turn.
//
// Errors:
//   - ErrSessionNotFound: no row for sessionID.
//   - wrapped sqlstore errors: lookup failures other than not-found.
//   - ErrBootFailed (wrapped): Boot's own failure modes (adapter resolve,
//     loopback setup, plant, etc).
//
// The returned *Session represents a NEW row (fresh sessID generated by
// the Manager's IDFn). The original session row is unchanged — its
// state/exit_code/ended_at remain whatever they were before ResumeSession
// fired. Operators / dashboards link the two via the resume_hint column
// (same provider session-id), and a future enhancement can stamp a
// SessionMeta key with the prior sessID for stronger linkage.
func (m *Manager) ResumeSession(ctx context.Context, sessionID string, opts ResumeOptions) (*Session, error) {
	if sessionID == "" {
		return nil, fmt.Errorf("agent.Manager.ResumeSession: sessionID required")
	}
	if m == nil || m.deps == nil || m.deps.Store == nil {
		return nil, fmt.Errorf("agent.Manager.ResumeSession: nil store")
	}
	if err := m.checkStopped(); err != nil {
		return nil, err
	}

	rec, err := m.deps.Store.GetSession(sessionID)
	if err != nil {
		if errors.Is(err, sqlstore.ErrSessionNotFound) {
			return nil, ErrSessionNotFound
		}
		return nil, fmt.Errorf("agent.Manager.ResumeSession: get session: %w", err)
	}

	// D4: SupportsResume is the single decision point. The declared
	// capability — not a runtime probe — picks the branch.
	caps := ProviderCapabilities(rec.Provider)

	projectID := ""
	if rec.ProjectID.Valid {
		projectID = rec.ProjectID.String
	}
	taskID := ""
	if rec.TaskID.Valid {
		taskID = rec.TaskID.String
	}

	bootOpts := Options{
		Mode:         ModeLongLived,
		AgentProfile: rec.AgentProfile,
		Workdir:      rec.Workdir,
		ProjectID:    projectID,
		TaskID:       taskID,
		// composeSystemPrompt prepends Options.SystemPrompt in front of
		// the agent-file persona so the DiagnosticNote (when set by α.5
		// stuck-task recovery) lands at the top of the resumed CLAUDE.md.
		SystemPrompt: opts.DiagnosticNote,
	}

	// Preserve the role tag the original boot used so the resumed
	// transcript's planted CLAUDE.md still announces the same role.
	// Convention: planstart stamps SessionMeta["role"] for orchestrator
	// boots (orchestrator.SessionMetaRole) — that key is the canonical
	// human-readable role tag. Boot's own Options.Role defaults to the
	// AgentProfile when empty, so falling through here is also safe.
	if meta := decodeMeta(rec.MetaJSON); len(meta) > 0 {
		if v := meta["role"]; v != "" {
			bootOpts.Role = v
		}
	}

	if caps.SupportsResume && len(rec.ResumeHint) > 0 {
		// State-based resume: thread the persisted provider session-id
		// through Options.ProviderSessionIDOverride. Boot stamps
		// StartOptions.SessionIDPreset; the per-provider adapter prepends
		// `--resume <id>` on the first turn (claude today).
		bootOpts.ProviderSessionIDOverride = string(rec.ResumeHint)
	}
	// SupportsResume=false (or true-but-no-resume-hint) → fresh-boot. The
	// adapter argv carries no --resume flag; the new session gets a new
	// provider session-id on first turn.

	sess, err := Boot(ctx, m.deps, bootOpts)
	if err != nil {
		return nil, err
	}
	return sess, nil
}
