// Package sessionmgr implements clockwork's long-lived agent session
// manager (CW-20260503-0014, S1.4). It wraps go-agent-sessions with
// SQLite persistence, lifecycle hooks, and an orphan-sweep on startup.
//
// Sessions outlive a single task: the orchestrator (S2) needs a session
// that lives for the duration of a plan, while reviewer/planner agents
// reuse the lifecycle surface for short-lived work. Per-task ephemeral
// sessions remain in `cliexec.Run` — sessionmgr is the durable peer.
//
// Out of scope (per ticket fences): inter-session messaging (broker,
// S1.3), tool-broker integration (executor wrapper, S1.5), sandbox
// restoration (Phase F), per-session workspace management.
package sessionmgr

import (
	"errors"
	"time"
)

// Status is the public, user-facing lifecycle state. Mirrors go-agent-
// sessions State plus a `crashed` value the manager records when the
// orphan sweep finds a row whose process is no longer alive after a
// daemon restart.
type Status string

const (
	StatusLaunching Status = "launching"
	StatusRunning   Status = "running"
	StatusDone      Status = "done"
	StatusFailed    Status = "failed"
	StatusCrashed   Status = "crashed"
)

// Terminal reports whether the status indicates the session has stopped.
func (s Status) Terminal() bool {
	switch s {
	case StatusDone, StatusFailed, StatusCrashed:
		return true
	}
	return false
}

// Session is the public snapshot of a registered session. The Manager
// returns these from Get/List; raw go-agent-sessions handles stay
// internal.
type Session struct {
	ID            string
	AgentProfile  string
	Provider      string
	RuntimeID     string
	RuntimeKind   string
	Workdir       string
	ProjectID     string
	TaskID        string
	Status        Status
	PID           int
	ExitCode      *int
	ResumeHint    []byte
	Meta          map[string]string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastActivity  time.Time
	EndedAt       *time.Time
}

// LaunchRequest describes a session to launch. AgentProfile resolves
// against the configured ProfileMap; the Manager picks the go-providers
// CLIAdapter based on profile.Provider. Workdir is the spawned process's
// cwd (boot dir for Claude; project root otherwise — caller decides).
//
// SessionMeta is opaque key/value metadata persisted with the session
// row; the Manager echoes it back via Session.Meta. Use it for caller-
// side correlation (e.g. `{"role": "orchestrator"}`).
//
// PromptInputs is reserved for callers that want to drive the session's
// first turn before returning from Launch; for the MVP scope of this
// ticket the manager does not consume it. SendInput is the post-launch
// surface.
type LaunchRequest struct {
	AgentProfile string
	ProjectID    string
	TaskID       string
	Workdir      string
	SystemPrompt string
	Env          []string
	SessionMeta  map[string]string
}

// CheckpointRequest captures a checkpoint at a point in time. Payload is
// opaque caller JSON; the Manager persists it verbatim alongside the
// underlying go-agent-sessions CheckpointHint (when the adapter exposes
// one). Note is a free-form annotation for operators.
type CheckpointRequest struct {
	SessionID string
	Payload   string
	Note      string
}

// Checkpoint is the public snapshot of a session_checkpoints row.
type Checkpoint struct {
	ID         string
	SessionID  string
	Payload    string
	ResumeHint []byte
	Note       string
	CreatedAt  time.Time
}

// ResumeRequest re-launches a session against a previously persisted
// checkpoint. The new session id is generated by the Manager; the
// CheckpointID identifies which checkpoint's resume_hint to feed the
// underlying adapter (when the adapter supports it).
type ResumeRequest struct {
	SessionID    string
	CheckpointID string // optional — when empty, the latest checkpoint is used
	// Overrides — when set, replace the resumed session's fields. When
	// empty, the values from the original session row are reused.
	AgentProfile string
	Workdir      string
	SystemPrompt string
	Env          []string
}

// Sentinel errors. Wrap with errors.Is at call sites.
var (
	// ErrSessionNotFound indicates the named session has no row in the
	// store.
	ErrSessionNotFound = errors.New("sessionmgr: session not found")

	// ErrSessionNotRunning indicates the session is registered in the
	// store but the in-memory entry is gone (already terminated, never
	// resumed, or the daemon restarted).
	ErrSessionNotRunning = errors.New("sessionmgr: session not running in this process")

	// ErrManagerStopped is returned after Shutdown.
	ErrManagerStopped = errors.New("sessionmgr: manager stopped")

	// ErrNoCheckpoint is returned by Resume when the requested checkpoint
	// (or any checkpoint, if no ID was supplied) is missing.
	ErrNoCheckpoint = errors.New("sessionmgr: no checkpoint available")

	// ErrAdapterNotFound indicates the launch profile names a provider
	// the registry can't resolve.
	ErrAdapterNotFound = errors.New("sessionmgr: adapter not registered for provider")
)
