/** @vitest-environment jsdom */
import { afterEach, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import type { ListPage, Task, Collection } from '@/lib/types'
const { listCollections, listCollectionTasks, listInboxTasks, removeTaskFromCollection, transitionTask, moveTask, addTaskToInbox, event } = vi.hoisted(() => ({ listCollections: vi.fn(), listCollectionTasks: vi.fn(), listInboxTasks: vi.fn(), removeTaskFromCollection: vi.fn(), transitionTask: vi.fn(), moveTask: vi.fn(), addTaskToInbox: vi.fn(), event: { current: null as unknown } }))
vi.mock('@/hooks/use-api', () => ({ useApi: () => ({ listCollections, listCollectionTasks, listInboxTasks, removeTaskFromCollection, transitionTask, moveTask, addTaskToInbox }) }))
vi.mock('@/hooks/use-sse', () => ({ useSSE: () => ({ lastEvent: event.current }) }))
import CollectionsPage from './CollectionsPage'
function page<T>(items: T[], total: number, next_cursor: string | null): ListPage<T> {
  return { items, meta: { returned: items.length, total, limit: 50, has_more: !!next_cursor, next_cursor } }
}
const collection = (id: string): Collection => ({ id, name: id, description: '', created_at: '2026-10-01', updated_at: '2026-10-01', archived_at: null })
const tasks = (start: number) => Array.from({ length: 50 }, (_, index) => ({ id: `T-${start + index}`, title: `Task ${start + index}`, priority: 2, status: 'todo', collection_id: 'COL-1' }) as Task)
afterEach(() => { cleanup(); vi.resetAllMocks(); event.current = null })
it('pages large collections and task cohorts only on explicit continuation', async () => {
  listCollections.mockResolvedValueOnce(page([collection('COL-1')], 75, 'collections-next')).mockResolvedValueOnce(page([collection('COL-2')], 75, null))
  listCollectionTasks.mockImplementation((id, query) => Promise.resolve(id === 'COL-1' ? page(tasks(query.cursor ? 50 : 0), 301, query.cursor ? null : 'tasks-next') : page([], 0, null)))
  listInboxTasks.mockResolvedValue(page([], 0, null))
  render(<MemoryRouter><CollectionsPage /></MemoryRouter>)
  await screen.findByText('Task 49')
  expect(listCollections).toHaveBeenCalledTimes(1)
  expect(listCollectionTasks).toHaveBeenCalledTimes(1)
  expect(screen.queryByText('Task 50')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Load more tasks' }))
  await screen.findByText('Task 99', {}, { timeout: 3000 })
  expect(listCollectionTasks.mock.calls[1][1]).toMatchObject({ cursor: 'tasks-next', sort_by: 'position', sort_dir: 'asc', include_total: true })
  expect(screen.getByText('Task 0')).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Load more collections' }))
  await waitFor(() => expect(listCollectionTasks).toHaveBeenCalledTimes(3))
  expect(listCollections.mock.calls[1][1]).toMatchObject({ cursor: 'collections-next', sort_by: 'created_at' })
})

it('uses server task search/status and resets the cursor cohort', async () => {
  listCollections.mockResolvedValue(page([collection('COL-1')], 1, null))
  listInboxTasks.mockResolvedValue(page([], 0, null))
  listCollectionTasks.mockImplementation((_id, query) => Promise.resolve(page(query.status || query.search ? [{ ...tasks(200)[0], title: 'Deep server match', status: 'doing' }] : tasks(0), 301, query.status || query.search ? null : 'next')))
  render(<MemoryRouter><CollectionsPage /></MemoryRouter>)
  await screen.findByText('Task 49')
  fireEvent.click(screen.getByRole('button', { name: 'Doing' }))
  await screen.findByText('Deep server match')
  expect(listCollectionTasks.mock.calls.at(-1)?.[1]).toMatchObject({ status: 'doing', cursor: undefined })
  expect(screen.queryByText('Task 0')).toBeNull()
  fireEvent.change(screen.getByRole('textbox', { name: 'Search collection tasks' }), { target: { value: 'deep' } })
  await waitFor(() => expect(listCollectionTasks.mock.calls.at(-1)?.[1]).toMatchObject({ search: 'deep', status: 'doing' }))
})

it('confirms the exact complete cohort, stops after failure and refreshes server truth', async () => {
  let rows = tasks(0).slice(0, 8)
  listCollections.mockResolvedValue(page([collection('COL-1')], 1, null))
  listInboxTasks.mockResolvedValue(page([], 0, null))
  listCollectionTasks.mockImplementation(() => Promise.resolve(page([...rows], rows.length, null)))
  removeTaskFromCollection.mockImplementation(async (_collection, id) => {
    if (id === 'T-0') throw new Error('membership changed')
    rows = rows.filter(row => row.id !== id)
  })
  render(<MemoryRouter><CollectionsPage /></MemoryRouter>)
  await screen.findByText('Task 7')
  fireEvent.click(screen.getByRole('button', { name: 'Actions for collection COL-1' }))
  fireEvent.click(await screen.findByRole('menuitem', { name: 'Clear collection tasks' }))
  expect(await screen.findByRole('heading', { name: 'Remove 8 tasks from "COL-1"?' })).toBeTruthy()
  expect(screen.getByText(/This only removes them from the collection/)).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Remove assignments' }))
  await screen.findByText(/Remove collection assignments: 3 removed, 1 failed, 4 not attempted/)
  expect(removeTaskFromCollection.mock.calls).toEqual([['COL-1', 'T-0'], ['COL-1', 'T-1'], ['COL-1', 'T-2'], ['COL-1', 'T-3']])
  await waitFor(() => expect(listCollectionTasks).toHaveBeenCalledTimes(2))
  await screen.findByText('Task 7')
  expect(screen.queryByText('Task 1')).toBeNull()
  expect(screen.getByText('T-0: membership changed')).toBeTruthy()
})

it('disables clear for incomplete, filtered and SSE-stale cohorts', async () => {
  listCollections.mockResolvedValue(page([collection('COL-1')], 1, null))
  listInboxTasks.mockResolvedValue(page([], 0, null))
  listCollectionTasks.mockImplementation((_id, query) => Promise.resolve(page(tasks(0).slice(0, 2), 301, query.status ? null : 'next')))
  const view = render(<MemoryRouter><CollectionsPage /></MemoryRouter>)
  await screen.findByText('Task 1')
  fireEvent.click(screen.getByRole('button', { name: 'Actions for collection COL-1' }))
  const clear = await screen.findByRole('menuitem', { name: 'Clear collection tasks' })
  expect(clear.getAttribute('aria-disabled')).toBe('true')
  expect(screen.getByText('Load remaining tasks before clearing this collection.')).toBeTruthy()
  fireEvent.keyDown(clear, { key: 'Escape' })
  fireEvent.click(screen.getByRole('button', { name: 'Doing' }))
  await waitFor(() => expect(listCollectionTasks.mock.calls.at(-1)?.[1].status).toBe('doing'))
  fireEvent.click(screen.getByRole('button', { name: 'Actions for collection COL-1' }))
  expect(await screen.findByText('Reset task filters before clearing this collection.')).toBeTruthy()
  fireEvent.keyDown(screen.getByRole('menuitem', { name: 'Clear collection tasks' }), { key: 'Escape' })
  event.current = { type: 'collection.task_added', data: {} }
  view.rerender(<MemoryRouter><CollectionsPage /></MemoryRouter>)
  fireEvent.click(screen.getByRole('button', { name: 'Actions for collection COL-1' }))
  expect(await screen.findByText('Refresh the loaded pages and wait for loading to finish.')).toBeTruthy()
  expect(removeTaskFromCollection).not.toHaveBeenCalled()
})

it('moves only checked IDs through the public collection API and reloads one page', async () => {
  listCollections.mockResolvedValue(page([collection('COL-1'), collection('COL-2')], 2, null))
  listInboxTasks.mockResolvedValue(page([], 0, null))
  listCollectionTasks.mockImplementation(id => Promise.resolve(page(id === 'COL-1' ? tasks(0).slice(0, 2) : [], 2, null)))
  moveTask.mockResolvedValue(undefined)
  render(<MemoryRouter><CollectionsPage /></MemoryRouter>)
  await screen.findByText('Task 1')
  fireEvent.click(screen.getByRole('checkbox', { name: 'Select Task 0' }))
  fireEvent.click(screen.getByRole('checkbox', { name: 'Select Task 1' }))
  fireEvent.click(screen.getByRole('button', { name: 'Move selected…' }))
  await screen.findByRole('heading', { name: 'Move 2 selected tasks' })
  fireEvent.click(await screen.findByRole('button', { name: /^COL-2$/ }))
  await screen.findByText(/Move tasks: 2 succeeded, 0 failed, 0 not attempted/)
  expect(moveTask.mock.calls).toEqual([['T-0', 'COL-2'], ['T-1', 'COL-2']])
  await waitFor(() => expect(listCollectionTasks).toHaveBeenCalledTimes(4))
  expect(listCollectionTasks.mock.calls.every(([, query]) => !query.cursor)).toBe(true)
})
