package sqlstore

import (
	"database/sql"
	"errors"
	"fmt"
	"time"
)

// ErrSessionNotFound is returned by GetSession / UpdateSession* when no
// matching row exists.
var ErrSessionNotFound = errors.New("session not found")

// SessionRecord mirrors a row in the `sessions` table (migration 023).
// Soft-FK fields (ProjectID, TaskID) are stored as nullable strings since
// SQLite does not enforce foreign keys by default in this codebase.
type SessionRecord struct {
	ID           string
	AgentProfile string
	Provider     string
	RuntimeID    string
	RuntimeKind  string
	Workdir      string
	ProjectID    sql.NullString
	TaskID       sql.NullString
	State        string
	PID          int
	ExitCode     sql.NullInt64
	ResumeHint   []byte
	MetaJSON     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastActivity time.Time
	EndedAt      sql.NullTime
}

const sessionSelectCols = `id, agent_profile, provider, runtime_id, runtime_kind,
	workdir, project_id, task_id, state, pid, exit_code, resume_hint, meta,
	created_at, updated_at, last_activity, ended_at`

func scanSession(row interface {
	Scan(...any) error
}) (*SessionRecord, error) {
	s := &SessionRecord{}
	err := row.Scan(
		&s.ID, &s.AgentProfile, &s.Provider, &s.RuntimeID, &s.RuntimeKind,
		&s.Workdir, &s.ProjectID, &s.TaskID, &s.State, &s.PID, &s.ExitCode,
		&s.ResumeHint, &s.MetaJSON, &s.CreatedAt, &s.UpdatedAt, &s.LastActivity,
		&s.EndedAt,
	)
	if err != nil {
		return nil, err
	}
	return s, nil
}

// CreateSession inserts a new session row in state='launching'. The caller
// supplies the ID (ULID generated by the manager). Returns the inserted
// record so the caller has the assigned timestamps.
func (s *Store) CreateSession(rec *SessionRecord) error {
	if rec.ID == "" {
		return fmt.Errorf("session id is required")
	}
	state := rec.State
	if state == "" {
		state = "launching"
	}
	meta := rec.MetaJSON
	if meta == "" {
		meta = "{}"
	}
	_, err := s.db.Exec(`
		INSERT INTO sessions (
			id, agent_profile, provider, runtime_id, runtime_kind,
			workdir, project_id, task_id, state, pid, meta
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		rec.ID, rec.AgentProfile, rec.Provider, rec.RuntimeID, rec.RuntimeKind,
		rec.Workdir, rec.ProjectID, rec.TaskID, state, rec.PID, meta,
	)
	if err != nil {
		return fmt.Errorf("insert session: %w", err)
	}
	rec.State = state
	rec.MetaJSON = meta
	return nil
}

// GetSession returns the session with the given ID, or ErrSessionNotFound.
func (s *Store) GetSession(id string) (*SessionRecord, error) {
	row := s.ReadDB().QueryRow(`SELECT `+sessionSelectCols+` FROM sessions WHERE id = ?`, id)
	rec, err := scanSession(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrSessionNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("scan session: %w", err)
	}
	return rec, nil
}

// SessionFilter narrows ListSessions. Zero-value fields are ignored.
type SessionFilter struct {
	State     string
	TaskID    string
	ProjectID string
	Limit     int
}

// ListSessions returns sessions matching the filter, newest-first.
func (s *Store) ListSessions(f SessionFilter) ([]*SessionRecord, error) {
	q := `SELECT ` + sessionSelectCols + ` FROM sessions`
	var args []any
	var clauses []string
	if f.State != "" {
		clauses = append(clauses, "state = ?")
		args = append(args, f.State)
	}
	if f.TaskID != "" {
		clauses = append(clauses, "task_id = ?")
		args = append(args, f.TaskID)
	}
	if f.ProjectID != "" {
		clauses = append(clauses, "project_id = ?")
		args = append(args, f.ProjectID)
	}
	for i, c := range clauses {
		if i == 0 {
			q += " WHERE " + c
		} else {
			q += " AND " + c
		}
	}
	q += " ORDER BY created_at DESC"
	if f.Limit > 0 {
		q += fmt.Sprintf(" LIMIT %d", f.Limit)
	}
	rows, err := s.ReadDB().Query(q, args...)
	if err != nil {
		return nil, fmt.Errorf("list sessions: %w", err)
	}
	defer rows.Close()
	var out []*SessionRecord
	for rows.Next() {
		rec, err := scanSession(rows)
		if err != nil {
			return nil, fmt.Errorf("scan session: %w", err)
		}
		out = append(out, rec)
	}
	return out, rows.Err()
}

// UpdateSessionState mutates the lifecycle columns. Updates updated_at and
// last_activity unconditionally; sets ended_at only on terminal states.
// pid=0 leaves the existing pid intact (passing 0 is the convention for
// "no change"); pass the live pid on Running transitions and on terminal
// transitions if the caller already has it.
func (s *Store) UpdateSessionState(id, state string, pid int, exit *int) error {
	if state == "" {
		return fmt.Errorf("state is required")
	}
	now := time.Now().UTC()
	var endedAt sql.NullTime
	switch state {
	case "done", "failed", "crashed":
		endedAt = sql.NullTime{Time: now, Valid: true}
	}
	var exitArg sql.NullInt64
	if exit != nil {
		exitArg = sql.NullInt64{Int64: int64(*exit), Valid: true}
	}
	var res sql.Result
	var err error
	if pid > 0 {
		res, err = s.db.Exec(`
			UPDATE sessions
			SET state = ?, pid = ?, exit_code = COALESCE(?, exit_code),
			    updated_at = ?, last_activity = ?,
			    ended_at = COALESCE(?, ended_at)
			WHERE id = ?`,
			state, pid, exitArg, now, now, endedAt, id)
	} else {
		res, err = s.db.Exec(`
			UPDATE sessions
			SET state = ?, exit_code = COALESCE(?, exit_code),
			    updated_at = ?, last_activity = ?,
			    ended_at = COALESCE(?, ended_at)
			WHERE id = ?`,
			state, exitArg, now, now, endedAt, id)
	}
	if err != nil {
		return fmt.Errorf("update session state: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrSessionNotFound
	}
	return nil
}

// TouchSession bumps last_activity and updated_at without changing state.
// Used by checkpoint emit and any caller that wants to record liveness
// without a state transition.
func (s *Store) TouchSession(id string) error {
	now := time.Now().UTC()
	res, err := s.db.Exec(`UPDATE sessions SET last_activity = ?, updated_at = ? WHERE id = ?`,
		now, now, id)
	if err != nil {
		return fmt.Errorf("touch session: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrSessionNotFound
	}
	return nil
}

// UpdateSessionResumeHint persists the latest CheckpointHint bytes on the
// session row. nil clears any existing hint.
func (s *Store) UpdateSessionResumeHint(id string, hint []byte) error {
	res, err := s.db.Exec(`UPDATE sessions SET resume_hint = ?, updated_at = ? WHERE id = ?`,
		hint, time.Now().UTC(), id)
	if err != nil {
		return fmt.Errorf("update session resume hint: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrSessionNotFound
	}
	return nil
}

// SweepStaleSessions marks sessions in `launching` or `running` states as
// `crashed` with exit_code=-1. Intended for a single call at daemon
// startup: any session still in a live state after a process restart is
// orphaned. Returns the number of rows updated.
//
// The caller may pass a filter callback to verify-and-spare specific rows
// (e.g. a session whose PID is still alive on a process check). When the
// callback is nil, every running/launching row is swept unconditionally.
func (s *Store) SweepStaleSessions(spare func(rec *SessionRecord) bool) (int, error) {
	rows, err := s.ReadDB().Query(`SELECT ` + sessionSelectCols + ` FROM sessions WHERE state IN ('launching','running')`)
	if err != nil {
		return 0, fmt.Errorf("sweep query: %w", err)
	}
	var stale []string
	for rows.Next() {
		rec, err := scanSession(rows)
		if err != nil {
			rows.Close()
			return 0, fmt.Errorf("sweep scan: %w", err)
		}
		if spare != nil && spare(rec) {
			continue
		}
		stale = append(stale, rec.ID)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return 0, err
	}
	if len(stale) == 0 {
		return 0, nil
	}
	now := time.Now().UTC()
	exit := -1
	count := 0
	for _, id := range stale {
		_, err := s.db.Exec(`
			UPDATE sessions
			SET state = 'crashed', exit_code = ?, updated_at = ?, ended_at = ?
			WHERE id = ?`, exit, now, now, id)
		if err != nil {
			return count, fmt.Errorf("sweep update %s: %w", id, err)
		}
		count++
	}
	return count, nil
}

// SessionCheckpointRecord mirrors a row in `session_checkpoints`.
type SessionCheckpointRecord struct {
	ID         string
	SessionID  string
	Payload    string
	ResumeHint []byte
	Note       string
	CreatedAt  time.Time
}

// CreateSessionCheckpoint inserts a checkpoint row.
func (s *Store) CreateSessionCheckpoint(rec *SessionCheckpointRecord) error {
	if rec.ID == "" {
		return fmt.Errorf("session checkpoint id is required")
	}
	if rec.SessionID == "" {
		return fmt.Errorf("session checkpoint session_id is required")
	}
	payload := rec.Payload
	if payload == "" {
		payload = "{}"
	}
	_, err := s.db.Exec(`
		INSERT INTO session_checkpoints (id, session_id, payload, resume_hint, note)
		VALUES (?, ?, ?, ?, ?)`,
		rec.ID, rec.SessionID, payload, rec.ResumeHint, rec.Note,
	)
	if err != nil {
		return fmt.Errorf("insert session checkpoint: %w", err)
	}
	rec.Payload = payload
	return nil
}

// ListSessionCheckpoints returns checkpoints for a session, newest-first.
func (s *Store) ListSessionCheckpoints(sessionID string, limit int) ([]*SessionCheckpointRecord, error) {
	q := `SELECT id, session_id, payload, resume_hint, note, created_at
		FROM session_checkpoints WHERE session_id = ? ORDER BY created_at DESC`
	if limit > 0 {
		q += fmt.Sprintf(" LIMIT %d", limit)
	}
	rows, err := s.ReadDB().Query(q, sessionID)
	if err != nil {
		return nil, fmt.Errorf("list session checkpoints: %w", err)
	}
	defer rows.Close()
	var out []*SessionCheckpointRecord
	for rows.Next() {
		rec := &SessionCheckpointRecord{}
		if err := rows.Scan(&rec.ID, &rec.SessionID, &rec.Payload, &rec.ResumeHint, &rec.Note, &rec.CreatedAt); err != nil {
			return nil, fmt.Errorf("scan session checkpoint: %w", err)
		}
		out = append(out, rec)
	}
	return out, rows.Err()
}

// GetSessionCheckpoint returns the checkpoint with the given ID, or
// (nil, nil) when not found. Used by ModeResume's per-checkpoint lookup
// path (CW-20260508-0001) — replaces the prior 1:N walk over recent
// sessions which silently broke once the session list grew past the page
// limit.
func (s *Store) GetSessionCheckpoint(checkpointID string) (*SessionCheckpointRecord, error) {
	row := s.ReadDB().QueryRow(`SELECT id, session_id, payload, resume_hint, note, created_at
		FROM session_checkpoints WHERE id = ?`, checkpointID)
	rec := &SessionCheckpointRecord{}
	err := row.Scan(&rec.ID, &rec.SessionID, &rec.Payload, &rec.ResumeHint, &rec.Note, &rec.CreatedAt)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("scan session checkpoint: %w", err)
	}
	return rec, nil
}

// LatestSessionCheckpoint returns the most recent checkpoint for the
// session, or (nil, nil) when none exist.
func (s *Store) LatestSessionCheckpoint(sessionID string) (*SessionCheckpointRecord, error) {
	row := s.ReadDB().QueryRow(`SELECT id, session_id, payload, resume_hint, note, created_at
		FROM session_checkpoints WHERE session_id = ? ORDER BY created_at DESC LIMIT 1`, sessionID)
	rec := &SessionCheckpointRecord{}
	err := row.Scan(&rec.ID, &rec.SessionID, &rec.Payload, &rec.ResumeHint, &rec.Note, &rec.CreatedAt)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("scan session checkpoint: %w", err)
	}
	return rec, nil
}
